name: Run Unit Tests

on: [push, pull_request]


jobs:
  test:
    runs-on: ubuntu-latest
    

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libasound2-dev pulseaudio
        python -m pip install --upgrade pip
        pip install pygame

    - name: Configure dummy audio driver
      run: |
        echo "SDL_AUDIODRIVER=dummy" >> $GITHUB_ENV

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage pytest

    - name: Run unit tests
      run: |
        xvfb-run -a coverage run -m pytest
        pytest xml


    - name: Coveralls
      uses: coverallsapp/github-action@v2
