name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev xvfb ffmpeg
        sudo apt-get install alsa-base alsa-utils

        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame coverage pytest

    - name: Run unit tests
      run: |
        xvfb-run -a coverage run -m pytest
        pytest xml


    - name: Coveralls
      uses: coverallsapp/github-action@v2
