name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Выберите версию Python, которую вы хотите использовать (например, 3.8)

    - name: Install dependencies
      run: |
        pip install pygame
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Build and run Tkinter app
      run: python main.py # Замените 'your_tkinter_app.py' на имя вашего файла с Tkinter приложением
